services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "bin/rails db:migrate db:seed && bin/rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/dry_beans_development

volumes:
  pgdata:
